# Generated by Django 6.0.3 on 2026-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='fecha_solicitud',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
