# Generated by Django 6.0.3 on 2026-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={},
        ),
        migrations.AlterField(
            model_name='historial_acciones',
            name='modulo',
            field=models.CharField(choices=[('productos', 'Productos'), ('categorias', 'Categorías'), ('insumos', 'Insumos'), ('proveedores', 'Proveedores'), ('entradas', 'Entradas'), ('salidas', 'Salidas'), ('calendario', 'Calendario'), ('inventario', 'Inventario'), ('bom', 'BOM/Recetas'), ('usuarios', 'Usuarios'), ('reportes', 'Reportes'), ('respaldos', 'Respaldos'), ('sistema', 'Sistema'), ('notificaciones', 'Notificaciones'), ('pedidos', 'Pedidos'), ('despachos', 'Despachos'), ('mantenimientos', 'Mantenimientos'), ('clientes', 'Clientes')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='mantenimiento',
            table='garantia',
        ),
    ]
