# Generated by Django 6.0.3 on 2026-03-21 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('activar', 'Activar'), ('inactivar', 'Inactivar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('exportar', 'Exportar'), ('importar', 'Importar'), ('respaldo', 'Respaldo'), ('restaurar', 'Restaurar')], max_length=20)),
                ('modulo', models.CharField(choices=[('productos', 'Productos'), ('categorias', 'Categorías'), ('insumos', 'Insumos'), ('proveedores', 'Proveedores'), ('entradas', 'Entradas'), ('salidas', 'Salidas'), ('calendario', 'Calendario'), ('inventario', 'Inventario'), ('bom', 'BOM/Recetas'), ('usuarios', 'Usuarios'), ('reportes', 'Reportes'), ('respaldos', 'Respaldos'), ('sistema', 'Sistema')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'db_table': 'historial_acciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
