# Generated by Django 6.0.3 on 2026-04-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='foto_perfil',
            new_name='foto_usua',
        ),
    ]
