# Generated by Django 5.2.8 on 2026-02-12 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_respaldo', models.CharField(choices=[('completo', 'Respaldo Completo'), ('parcial', 'Respaldo Parcial'), ('incremental', 'Respaldo Incremental')], default='completo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(default='admin', max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'db_table': 'respaldos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 10 dígitos', regex='^\\d{7,10}$')]),
        ),
    ]
