# Generated by Django 5.2.8 on 2026-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True, blank=True),
        ),
    ]
