# Generated by Django 6.0.4 on 2026-04-30 00:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garantia',
            options={'verbose_name': 'Garantía', 'verbose_name_plural': 'Garantías'},
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='es_especial',
            field=models.BooleanField(default=False, verbose_name='Cliente Especial (Plazo extendido)'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='despacho',
            name='empresa_transporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Guía'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='es_personalizado',
            field=models.BooleanField(default=False, verbose_name='Es personalizado'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='especificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Especificaciones del cliente'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='descripcion_falla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='estado_reparacion',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('en_reparacion', 'En Reparación'), ('reparada', 'Reparada'), ('entregada', 'Entregada al cliente')], default='recibida', max_length=20),
        ),
        migrations.AddField(
            model_name='garantia',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='garantia',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pedido'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_limite_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago'),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
