# Generated by Django 6.0.2 on 2026-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=100)),
                ('tipo_respaldo', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='respaldos_sql/')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'db_table': 'respaldos',
                'ordering': ['-fecha'],
            },
        ),
    ]
