# Generated by Django 5.2.8 on 2025-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuar',
            new_name='nombre_usuario',
        ),
    ]
