# Generated by Django 6.0.4 on 2026-05-06 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mantenimiento",
            options={
                "verbose_name": "Mantenimiento",
                "verbose_name_plural": "Mantenimientos",
            },
        ),
        migrations.AddField(
            model_name="mantenimiento",
            name="estado",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mantenimiento",
            name="descripcion_falla",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mantenimiento",
            name="estado_reparacion",
            field=models.CharField(
                choices=[
                    ("recibida", "Recibida"),
                    ("en_reparacion", "En Reparación"),
                    ("reparada", "Reparada"),
                    ("entregada", "Entregada al cliente"),
                ],
                default="recibida",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mantenimiento",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mantenimiento",
            name="producto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.producto",
            ),
        ),
        migrations.AlterModelTable(
            name="mantenimiento",
            table="mantenimientos",
        ),
    ]
