# Generated by Django 5.2.11 on 2026-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('entrega', 'Entrega de Pedido'), ('entrega_insumo', 'Entrega de insumo'), ('reunion_interna', 'Reunión Interna'), ('reunion', 'Reunión con Cliente'), ('otro', 'Otro')], max_length=20)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
            },
        ),
    ]
