# Generated by Django 5.2.11 on 2026-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
