# Generated by Django 5.2.8 on 2025-12-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nombre_usuar_usuario_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
