# Generated by Django 6.0.4 on 2026-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_garantia_options_remove_garantia_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('bajo_stock_insumo', 'Bajo stock insumo'), ('bajo_stock_producto', 'Bajo stock producto'), ('calendario_hoy', 'Evento Calendario HOY'), ('calendario_manaña', 'Evento Calendario MAÑANA'), ('pendido_despacho', 'Despacho pendiente'), ('sin_bom', 'Producto sin receta BOM'), ('reporte_generado', 'Reporte generado'), ('despacho_completado', 'Despacho completado'), ('pago_pendiente', 'Pedido pago pendiente'), ('garantia_nueva', 'Nueva Garantía Registrada')], max_length=30),
        ),
    ]
