# Generated by Django 6.0.3 on 2026-03-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historial_acciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('producto_bajo', 'Producto bajo stock'), ('evento_hoy', 'Evento hoy'), ('evento_manana', 'Evento mañana'), ('evento_vencido', 'Evento vencido')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('relacionada_id', models.PositiveIntegerField(blank=True, null=True)),
                ('relacionada_tipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_notificacion'],
            },
        ),
    ]
