# Generated by Django 6.0.4 on 2026-04-29 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_notif'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_notificacion',
            new_name='fecha_notif',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='relacionada_id',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='relacionada_tipo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='data_json',
            field=models.JSONField(blank=True, default=dict, help_text='Datos extra: {producto_id:1, stock:3}'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del modelo relacionado', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historial_acciones',
            name='modulo',
            field=models.CharField(choices=[('productos', 'Productos'), ('categorias', 'Categorías'), ('insumos', 'Insumos'), ('proveedores', 'Proveedores'), ('entradas', 'Entradas'), ('salidas', 'Salidas'), ('calendario', 'Calendario'), ('inventario', 'Inventario'), ('bom', 'BOM/Recetas'), ('usuarios', 'Usuarios'), ('reportes', 'Reportes'), ('respaldos', 'Respaldos'), ('sistema', 'Sistema'), ('notificaciones', 'Notificaciones')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('bajo_stock_insumo', 'Bajo stock insumo'), ('bajo_stock_producto', 'Bajo stock producto'), ('calendario_hoy', 'Evento Calendario HOY'), ('calendario_manana', 'Evento Calendario MAÑANA'), ('pendido_despacho', 'Despacho pendiente'), ('sin_bom', 'Producto sin receta BOM'), ('reporte_generado', 'Reporte generado'), ('despacho_completado', 'Despacho completado'), ('pago_pendiente', 'Pedido pago pendiente')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leida', 'fecha_notif'], name='notificacio_leida_3ab474_idx'),
        ),
    ]
