# Generated by Django 6.0.2 on 2026-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_respaldo_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del proveedor', null=True, upload_to='proveedores/'),
        ),
    ]
