# Generated by Django 6.0.2 on 2026-02-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_producto_tipo_producto_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='detalle_pedido',
        ),
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'bom (Estructura de Producto)', 'verbose_name_plural': 'boms'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={'verbose_name': 'despacho', 'verbose_name_plural': 'despachos'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'insumo', 'verbose_name_plural': 'insumos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'reporte', 'verbose_name_plural': 'reportes'},
        ),
        migrations.AlterModelOptions(
            name='supervision',
            options={'verbose_name': 'supervisión', 'verbose_name_plural': 'supervisiones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/'),
        ),
    ]
