# Generated by Django 6.0.2 on 2026-02-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_calendario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
