# Generated by Django 5.2.11 on 2026-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('insumo', 'Insumo')], default='producto', max_length=20),
        ),
    ]
