# Generated by Django 5.2.11 on 2026-02-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventos_calendario_delete_evento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventos_calendario',
            new_name='evento_calendario',
        ),
    ]
