# Generated by Django 6.0.2 on 2026-02-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_calendario_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='activo',
        ),
        migrations.AddField(
            model_name='calendario',
            name='modo_completado',
            field=models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='automatico', max_length=15),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('eliminado', 'Eliminado')], default='pendiente', max_length=20),
        ),
    ]
