# Generated by Django 6.0.3 on 2026-03-23 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_telefono'),
        ('app', '0003_notificacion'),
    ]

    operations = [
    ]
