# Generated by Django 6.0.3 on 2026-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
    ]
