# Generated by Django 5.2.11 on 2026-02-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_eventos_calendario_evento_calendario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evento_calendario',
        ),
    ]
