# Generated by Django 6.0.2 on 2026-02-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto_imagen_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respaldo',
            name='archivo',
            field=models.FileField(default=0, upload_to='respaldos_sql/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respaldo',
            name='tipo_respaldo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='respaldo',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
