# Generated by Django 6.0.2 on 2026-02-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_compra_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='precio_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='precio_unidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
