# Generated by Django 6.0.3 on 2026-03-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoria_tipo'),
        ('app', '0004_add_anulado_to_entrada'),
    ]

    operations = [
    ]
