# Generated by Django 6.0.3 on 2026-03-10 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0003_categoria_tipo_0004_add_anulado_to_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='salida_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='app.producto')),
            ],
            options={
                'verbose_name': 'Salida de Producto',
                'verbose_name_plural': 'Salidas de Productos',
                'db_table': 'salida_producto',
                'ordering': ['-fecha'],
            },
        ),
    ]
