# Generated by Django 5.2.11 on 2026-02-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_evento_calendario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evento_calendario',
        ),
    ]
