# Generated by Django 5.2.11 on 2026-03-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuario_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bom',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto', unique=True),
        ),
    ]
