# Generated by Django 6.0.2 on 2026-02-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_evento_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('categoria', models.CharField(choices=[('pago', 'Pago'), ('compra', 'Compra'), ('pedido', 'Pedido')], max_length=50)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
                'db_table': 'calendario',
            },
        ),
    ]
