# Generated by Django 5.2.11 on 2026-03-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_bom_unique_together_alter_bom_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('producto', 'insumo')},
        ),
    ]
